services:
  wakapi:
    image: ghcr.io/muety/wakapi:2.12.3
    # ports:
    #   - 3000:3000
    restart: unless-stopped
    environment:
      # See README.md and config.default.yml for all config options
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_HOST: "db"
      WAKAPI_DB_PORT: "5432"
      WAKAPI_DB_PASSWORD: ${WAKAPI_DB_PASSWORD}
      WAKAPI_PASSWORD_SALT: ${WAKAPI_PASSWORD_SALT}
      WAKAPI_MAIL_SMTP_PASS: ${WAKAPI_MAIL_SMTP_PASS}
      WAKAPI_ALLOW_SIGNUP: "false"

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_PASSWORD: ${WAKAPI_DB_PASSWORD}
      POSTGRES_DB: "wakapi"
    volumes:
      - ./volume/db:/var/lib/postgresql/data
